/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MASTEREK_NETBEANS;

/**
 *
 * @author Sonia
 */
public class newFrame extends javax.swing.JDialog {

    /**
     * Creates new form newFrame
     */
    public newFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorChoice = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        slot1 = new javax.swing.JButton();
        redChoice = new javax.swing.JRadioButton();
        yellowChoice = new javax.swing.JRadioButton();
        purpleChoice = new javax.swing.JRadioButton();
        blueChoice = new javax.swing.JRadioButton();
        greenChoice = new javax.swing.JRadioButton();
        slot2 = new javax.swing.JButton();
        slot3 = new javax.swing.JButton();
        slot4 = new javax.swing.JButton();
        orangeChoice = new javax.swing.JRadioButton();
        pinkChoice = new javax.swing.JRadioButton();
        whiteChoice = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MasterMind");
        setBackground(new java.awt.Color(204, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusableWindowState(false);
        setSize(new java.awt.Dimension(550, 650));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setText("MASTERMIND");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        slot1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulapusta.png")); // NOI18N
        slot1.setContentAreaFilled(false);
        slot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slot1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slot1MouseReleased(evt);
            }
        });

        colorChoice.add(redChoice);
        redChoice.setToolTipText("");
        redChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kuladajefula.png")); // NOI18N
        redChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redChoiceActionPerformed(evt);
            }
        });

        colorChoice.add(yellowChoice);
        yellowChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yellowChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulazolta.png")); // NOI18N
        yellowChoice.setPreferredSize(new java.awt.Dimension(32, 32));

        colorChoice.add(purpleChoice);
        purpleChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        purpleChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulafioletowa.png")); // NOI18N
        purpleChoice.setPreferredSize(new java.awt.Dimension(32, 32));
        purpleChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleChoiceActionPerformed(evt);
            }
        });

        colorChoice.add(blueChoice);
        blueChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blueChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulaniebieska.png")); // NOI18N
        blueChoice.setPreferredSize(new java.awt.Dimension(32, 32));

        colorChoice.add(greenChoice);
        greenChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        greenChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulazielona.png")); // NOI18N
        greenChoice.setPreferredSize(new java.awt.Dimension(32, 32));

        slot2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulapusta.png")); // NOI18N
        slot2.setContentAreaFilled(false);
        slot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slot2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slot2MouseReleased(evt);
            }
        });

        slot3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulapusta.png")); // NOI18N
        slot3.setContentAreaFilled(false);
        slot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slot3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slot3MouseReleased(evt);
            }
        });

        slot4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulapusta.png")); // NOI18N
        slot4.setContentAreaFilled(false);
        slot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slot4MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slot4MouseReleased(evt);
            }
        });

        colorChoice.add(orangeChoice);
        orangeChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orangeChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulapomaranczowa.png")); // NOI18N
        orangeChoice.setPreferredSize(new java.awt.Dimension(32, 32));

        colorChoice.add(pinkChoice);
        pinkChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pinkChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kularozowa.png")); // NOI18N
        pinkChoice.setPreferredSize(new java.awt.Dimension(32, 32));

        colorChoice.add(whiteChoice);
        whiteChoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        whiteChoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sonia\\Downloads\\kulabiala.png")); // NOI18N
        whiteChoice.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(redChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yellowChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purpleChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blueChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(whiteChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orangeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(greenChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinkChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(redChoice)
                                        .addComponent(yellowChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(blueChoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(whiteChoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(orangeChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purpleChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(574, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(greenChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pinkChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
        );

        jLabel1.getAccessibleContext().setAccessibleName("label1");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void slot1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot1MouseReleased

    }//GEN-LAST:event_slot1MouseReleased

    private void redChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redChoiceActionPerformed

    private void slot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot1MouseClicked
      //for(newFrame choice: colorChoice){
        if(yellowChoice.isSelected()){
        slot1.setIcon(yellowChoice.getIcon());
        }
        if(redChoice.isSelected()){
        slot1.setIcon(redChoice.getIcon());
        }
        if(greenChoice.isSelected()){
        slot1.setIcon(greenChoice.getIcon());
        }
        if(blueChoice.isSelected()){
        slot1.setIcon(blueChoice.getIcon());
        }
        if(pinkChoice.isSelected()){
        slot1.setIcon(pinkChoice.getIcon());
        }
        if(orangeChoice.isSelected()){
        slot1.setIcon(orangeChoice.getIcon());
        }
        if(purpleChoice.isSelected()){
        slot1.setIcon(purpleChoice.getIcon());
        }
        if(whiteChoice.isSelected()){
        slot1.setIcon(whiteChoice.getIcon());
        }
      //}
    }//GEN-LAST:event_slot1MouseClicked

    private void slot2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot2MouseClicked
        if(yellowChoice.isSelected()){
        slot2.setIcon(yellowChoice.getIcon());
        }
        if(redChoice.isSelected()){
        slot2.setIcon(redChoice.getIcon());
        }
        if(greenChoice.isSelected()){
        slot2.setIcon(greenChoice.getIcon());
        }
        if(blueChoice.isSelected()){
        slot2.setIcon(blueChoice.getIcon());
        }
        if(pinkChoice.isSelected()){
        slot2.setIcon(pinkChoice.getIcon());
        }
        if(orangeChoice.isSelected()){
        slot2.setIcon(orangeChoice.getIcon());
        }
        if(purpleChoice.isSelected()){
        slot2.setIcon(purpleChoice.getIcon());
        }
        if(whiteChoice.isSelected()){
        slot2.setIcon(whiteChoice.getIcon());
        }
    }//GEN-LAST:event_slot2MouseClicked

    private void slot2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_slot2MouseReleased

    private void slot3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot3MouseClicked
        if(yellowChoice.isSelected()){
        slot3.setIcon(yellowChoice.getIcon());
        }
        if(redChoice.isSelected()){
        slot3.setIcon(redChoice.getIcon());
        }
        if(greenChoice.isSelected()){
        slot3.setIcon(greenChoice.getIcon());
        }
        if(blueChoice.isSelected()){
        slot3.setIcon(blueChoice.getIcon());
        }
        if(pinkChoice.isSelected()){
        slot3.setIcon(pinkChoice.getIcon());
        }
        if(orangeChoice.isSelected()){
        slot3.setIcon(orangeChoice.getIcon());
        }
        if(purpleChoice.isSelected()){
        slot3.setIcon(purpleChoice.getIcon());
        }
        if(whiteChoice.isSelected()){
        slot3.setIcon(whiteChoice.getIcon());
        }
    }//GEN-LAST:event_slot3MouseClicked

    private void slot3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_slot3MouseReleased

    private void slot4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot4MouseClicked
        if(yellowChoice.isSelected()){
        slot4.setIcon(yellowChoice.getIcon());
        }
        if(redChoice.isSelected()){
        slot4.setIcon(redChoice.getIcon());
        }
        if(greenChoice.isSelected()){
        slot4.setIcon(greenChoice.getIcon());
        }
        if(blueChoice.isSelected()){
        slot4.setIcon(blueChoice.getIcon());
        }
        if(pinkChoice.isSelected()){
        slot4.setIcon(pinkChoice.getIcon());
        }
        if(orangeChoice.isSelected()){
        slot4.setIcon(orangeChoice.getIcon());
        }
        if(purpleChoice.isSelected()){
        slot4.setIcon(purpleChoice.getIcon());
        }
        if(whiteChoice.isSelected()){
        slot4.setIcon(whiteChoice.getIcon());
        }
    }//GEN-LAST:event_slot4MouseClicked

    private void slot4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slot4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_slot4MouseReleased

    private void purpleChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purpleChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                newFrame dialog = new newFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blueChoice;
    private javax.swing.ButtonGroup colorChoice;
    private javax.swing.JRadioButton greenChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton orangeChoice;
    private javax.swing.JRadioButton pinkChoice;
    private javax.swing.JRadioButton purpleChoice;
    private javax.swing.JRadioButton redChoice;
    private javax.swing.JButton slot1;
    private javax.swing.JButton slot2;
    private javax.swing.JButton slot3;
    private javax.swing.JButton slot4;
    private javax.swing.JRadioButton whiteChoice;
    private javax.swing.JRadioButton yellowChoice;
    // End of variables declaration//GEN-END:variables
}
